name: struct2text_env
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - mkl=2024.0
    - pip
    - pip:
        - numpy
        - opendelta
        - pandas
        - sentencepiece>=0.1.96
        - tqdm>=4.62.2
        - transformers>=4.10.0,<=4.27.1
        - datasets>=1.17.0
        - evaluate
        - nltk
        - wandb
        - accelerate
    - pytorch::pytorch=1.12.1
